-- Sample Investors
INSERT INTO profiles (id, role, full_name, email, headline, location, firm, check_size_min, check_size_max, focus_sectors, focus_stages, focus_markets, verification, prompts, photos, dealbreakers, created_at, updated_at)
VALUES 
  (gen_random_uuid(), 'investor', 'Alex Chen', 'alex.chen@sequoia.vc', 'Partner at Sequoia Capital', 'San Francisco, CA', 'Sequoia Capital', 500000, 5000000, '["AI/ML","Enterprise SaaS","Fintech"]', '["Seed","Series A"]', '[]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'investor', 'Sarah Johnson', 'sarah.j@a16z.com', 'Principal at Andreessen Horowitz', 'Menlo Park, CA', 'Andreessen Horowitz', 1000000, 10000000, '["Web3","Crypto","Infrastructure"]', '["Pre-seed","Seed","Series A"]', '[]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'investor', 'Michael Park', 'mike.park@ycombinator.com', 'Partner at Y Combinator', 'Mountain View, CA', 'Y Combinator', 125000, 500000, '["Consumer","Marketplaces","AI"]', '["Pre-seed"]', '[]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'investor', 'Emma Rodriguez', 'emma@firstround.com', 'Partner at First Round Capital', 'San Francisco, CA', 'First Round Capital', 250000, 2000000, '["Healthcare","BioTech","Marketplaces"]', '["Seed","Series A"]', '[]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'investor', 'David Kim', 'david@lightspeed.vc', 'Partner at Lightspeed Venture Partners', 'Palo Alto, CA', 'Lightspeed Venture Partners', 500000, 5000000, '["Enterprise","Security","Developer Tools"]', '["Seed","Series A","Series B"]', '[]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW());

-- Sample Founders
INSERT INTO profiles (id, role, full_name, email, headline, location, company_name, company_url, revenue_run_rate, team_size, runway_months, focus_sectors, focus_stages, focus_markets, verification, prompts, photos, dealbreakers, created_at, updated_at)
VALUES 
  (gen_random_uuid(), 'founder', 'Jamie Taylor', 'jamie@techstartup.io', 'Founder & CEO at TechStartup', 'Austin, TX', 'TechStartup', 'https://techstartup.io', 1200000, 12, 18, '["SaaS","B2B"]', '["Seed"]', '["US","Canada"]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'founder', 'Casey Martinez', 'casey@aihealth.ai', 'Co-founder at AIHealth', 'Boston, MA', 'AIHealth', 'https://aihealth.ai', 2400000, 18, 12, '["Healthcare","AI/ML"]', '["Series A"]', '["US"]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'founder', 'Jordan Lee', 'jordan@cryptopay.com', 'Founder at CryptoPay', 'New York, NY', 'CryptoPay', 'https://cryptopay.com', 500000, 8, 24, '["Fintech","Web3"]', '["Seed"]', '["Global"]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'founder', 'Riley Chen', 'riley@edutech.io', 'CEO at EduTech', 'Seattle, WA', 'EduTech', 'https://edutech.io', 1800000, 15, 15, '["EdTech","Consumer"]', '["Series A"]', '["US","UK","Australia"]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW()),
  (gen_random_uuid(), 'founder', 'Taylor Brown', 'taylor@greentech.co', 'Co-founder at GreenTech', 'Portland, OR', 'GreenTech', 'https://greentech.co', 900000, 10, 20, '["CleanTech","Enterprise"]', '["Seed"]', '["US","Europe"]', '{"soft_verified": true, "badges": ["verified_email"]}', '[]', '[]', '[]', NOW(), NOW());
