"""add_hinge_features_photos_dealbreakers_pass_daily_limits

Revision ID: cafcde9b8cc6
Revises: 3aeff2fffeff
Create Date: 2025-11-30 20:14:49.638514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cafcde9b8cc6'
down_revision: Union[str, None] = '3aeff2fffeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns to existing tables
    op.add_column('likes', sa.Column('prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('likes', sa.Column('like_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='standard'))
    op.add_column('matches', sa.Column('match_outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profiles', sa.Column('photos', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('profiles', sa.Column('dealbreakers', sa.JSON(), nullable=False, server_default='{}'))

    # Create new tables
    op.create_table('passes',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('passed_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
        sa.ForeignKeyConstraint(['passed_profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passes_id'), 'passes', ['id'], unique=False)
    op.create_index(op.f('ix_passes_user_id'), 'passes', ['user_id'], unique=False)
    op.create_index(op.f('ix_passes_created_at'), 'passes', ['created_at'], unique=False)

    op.create_table('profile_views',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('viewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('viewed_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['viewer_id'], ['profiles.id'], ),
        sa.ForeignKeyConstraint(['viewed_profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_views_id'), 'profile_views', ['id'], unique=False)
    op.create_index(op.f('ix_profile_views_viewer_id'), 'profile_views', ['viewer_id'], unique=False)
    op.create_index(op.f('ix_profile_views_created_at'), 'profile_views', ['created_at'], unique=False)

    op.create_table('daily_limits',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('standard_likes_used', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('roses_used', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('standard_likes_limit', sa.Integer(), nullable=False, server_default='10'),
        sa.Column('roses_limit', sa.Integer(), nullable=False, server_default='1'),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_limits_id'), 'daily_limits', ['id'], unique=False)
    op.create_index(op.f('ix_daily_limits_profile_id'), 'daily_limits', ['profile_id'], unique=False)
    op.create_index(op.f('ix_daily_limits_date'), 'daily_limits', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop new tables
    op.drop_index(op.f('ix_daily_limits_date'), table_name='daily_limits')
    op.drop_index(op.f('ix_daily_limits_profile_id'), table_name='daily_limits')
    op.drop_index(op.f('ix_daily_limits_id'), table_name='daily_limits')
    op.drop_table('daily_limits')

    op.drop_index(op.f('ix_profile_views_created_at'), table_name='profile_views')
    op.drop_index(op.f('ix_profile_views_viewer_id'), table_name='profile_views')
    op.drop_index(op.f('ix_profile_views_id'), table_name='profile_views')
    op.drop_table('profile_views')

    op.drop_index(op.f('ix_passes_created_at'), table_name='passes')
    op.drop_index(op.f('ix_passes_user_id'), table_name='passes')
    op.drop_index(op.f('ix_passes_id'), table_name='passes')
    op.drop_table('passes')

    # Drop new columns
    op.drop_column('profiles', 'dealbreakers')
    op.drop_column('profiles', 'photos')
    op.drop_column('matches', 'match_outcome')
    op.drop_column('likes', 'like_type')
    op.drop_column('likes', 'prompt_id')

    # ### end Alembic commands ###

